sync a lot of things

diff --git a/step2bak.ctagfit/makefile.3fits_btagcut_psuedodata b/step2bak.ctagfit/makefile.3fits_btagcut_psuedodata
--- a/step2bak.ctagfit/makefile.3fits_btagcut_psuedodata
+++ b/step2bak.ctagfit/makefile.3fits_btagcut_psuedodata
@@ -1,8 +1,7 @@
 oDIR ?= output
-iYAML ?= test.btag_psuedofit.yaml
-iYAMLbtag ?= test.btag_psuedofit_btag.yaml
-iYAMLcvsb ?= test.btag_psuedofit_cvsb.yaml
-iYAMLcvsl ?= test.btag_psuedofit_cvsl.yaml
+iYAMLbtag ?= source.btag_psuedofit_btag.yaml
+iYAMLcvsb ?= source.btag_psuedofit_cvsb.yaml
+iYAMLcvsl ?= source.btag_psuedofit_cvsl.yaml
 #iYAMLBDT  ?= test.btag_psuedofit_BDTAll.yaml
 self=makefile.3fits_btagcut_psuedodata
 
@@ -56,10 +55,6 @@ step10_prepare_histograms:  clean-odir $(oDIR) ## Create histograms for [oDIR=ou
 		combineCards.py  btag=psuedofit_datacard_btag.txt cvsl=psuedofit_datacard_cvsl.txt cvsb=psuedofit_datacard_cvsb.txt > $(_TMP_DATACARD)
 
 
-check1_makehisto_content: ## Create secondary rootfile for checking makehisto.root is correct or not
-	$(call check_dir_existed,$(oDIR))
-	cd $(oDIR) && python3 ../secondary_plot_creation.py ../$(iYAML) ; echo ERROR!!!! iYAML is not a valid configuration in makefile
-	#cd $(oDIR) && DrawRatioPlotablesWithCMSFormat.py ../input.check.yaml
 
 
 _TMP_DATACARD        := psuedofit_datacard.txt
@@ -80,11 +75,10 @@ step2_text2workspace: ## create workspace for combine
 
 step3_combine: ## combine fitting result
 	$(call check_dir_existed,$(oDIR))
-	cd $(oDIR) && combine --saveWorkspace -M MultiDimFit -d $(_TMP_INPUT_WORKSPACE) --saveFitResult --saveNLL --robustFit on || the_exit "failed to run combine @ data sideband"
-	cd $(oDIR) && mv multidimfitTest.root $(_TMP_MULTIDIMFITTEST) ; mv higgsCombineTest.MultiDimFit.mH120.root $(_TMP_HIGGSCOMBINETEST)
+	cd $(oDIR) && combine --saveWorkspace -M MultiDimFit -d $(_TMP_INPUT_WORKSPACE) --saveFitResult --saveNLL --robustFit on -n SimulFit || the_exit "failed to run combine @ data sideband"
 
-_TMP_MULTIDIMFITTEST  := psuedofit_multidimfitTest.root
-_TMP_HIGGSCOMBINETEST := psuedofit_higgsCombineTest.MultiDimFit.mH120.root
+_TMP_MULTIDIMFITTEST  := multidimfitSimulFit.root
+_TMP_HIGGSCOMBINETEST := higgsCombineSimulFit.MultiDimFit.mH120.root
 OUT_FITINFO           := psuedofit_fitinfo.yaml
 POSTFIT_ROOT          := psuedofit_postfit.root
 step4_postfit: ## postfit for visualization
@@ -111,10 +105,50 @@ check4_postfit: ## check plot on postfit
 	#cd $(oDIR) && DrawRatioPlotablesWithCMSFormat.py ../input.check.postfit.psuedodata.btag.yaml && \
 	
 
-check5_checktruth: ## check truth value
+OUT_FITINFO_BASHVAR := psuedofit_fitinfo_bashvar.sh
+step5_profiledLL:
 	$(call check_dir_existed,$(oDIR))
-	cd $(oDIR) && python3 ../compare_truth_and_fit_value.py $(iYAMLcvsb) $(_TMP_HIGGSCOMBINETEST) numL numC numB # The result for iYAMLbtag / iYAMLcvsb / iYAMLcvsl are the same
-	#cd $(oDIR) && python3 ../compare_truth_and_fit_value.py $(iYAMLbtag) $(_TMP_HIGGSCOMBINETEST) numL numC numB numFAKE # The result for iYAMLbtag / iYAMLcvsb / iYAMLcvsl are the same
+	cd $(oDIR) && python3 ../convert_yamlvar_to_bashval.py $(OUT_FITINFO) $(OUT_FITINFO_BASHVAR)
+	cd $(oDIR) && source ./$(OUT_FITINFO_BASHVAR) && \
+		 combine -M MultiDimFit $(_TMP_HIGGSCOMBINETEST) --robustFit 1 --algo grid --points 300 --setParameterRanges numC=$${numC_rangeL},$${numC_rangeR} -P numC -n _scan_numC && \
+		 ../plot1DScan.py --POI numC higgsCombine_scan_numC.MultiDimFit.mH120.root -o scan.numC
+	cd $(oDIR) && source ./$(OUT_FITINFO_BASHVAR) && \
+		 combine -M MultiDimFit $(_TMP_HIGGSCOMBINETEST) --robustFit 1 --algo grid --points 300 --setParameterRanges numB=$${numB_rangeL},$${numB_rangeR} -P numB -n _scan_numB && \
+		 ../plot1DScan.py --POI numB higgsCombine_scan_numB.MultiDimFit.mH120.root -o scan.numB
+
+OUT_FITINFO_BASHVAR_2nd := psuedofit_fitinfo_2ndSimulFit_bashvar.sh
+_TMP_INPUT_WORKSPACE_2nd := psuedofit_ws_2ndSimulFit.root
+_TMP_MULTIDIMFITTEST_2nd  := multidimfit2ndSimulFit.root
+_TMP_HIGGSCOMBINETEST_2nd := higgsCombine2ndSimulFit.MultiDimFit.mH120.root
+
+
+step6_combinetwice:
+	cd $(oDIR) && python3 ../convert_yamlvar_to_bashval.py scan.numC.yaml scan.numC.fitval.sh
+	cd $(oDIR) && python3 ../convert_yamlvar_to_bashval.py scan.numB.yaml scan.numB.fitval.sh
+	cd $(oDIR) && source ./$(OUT_FITINFO_BASHVAR) && \
+	    source ./scan.numC.fitval.sh && source ./scan.numB.fitval.sh && \
+		echo "numL: $${numL_central},$${numL_rangeL},$${numL_rangeR}" && \
+		echo "numC: $${numC_central},$${numC_rangeL},$${numC_rangeR}" && \
+		echo "numB: $${numB_central},$${numB_rangeL},$${numB_rangeR}" && \
+		text2workspace.py $(_TMP_DATACARD) -o $(_TMP_INPUT_WORKSPACE_2nd) \
+    	-P HiggsAnalysis.CombinedLimit.PhysicsModel:multiSignalModel \
+    	--PO "map=.*/Ljet:numL[$${numL_central},$${numL_rangeL},$${numL_rangeR}]" \
+    	--PO "map=.*/Cjet:numC[$${numC_central},$${numC_rangeL},$${numC_rangeR}]" \
+    	--PO "map=.*/Bjet:numB[$${numB_central},$${numB_rangeL},$${numB_rangeR}]" \
+    	--PO verbose || (echo "failed to create workspace from datacard"; exit 1)
+	cd $(oDIR) && combine --saveWorkspace -M MultiDimFit -d $(_TMP_INPUT_WORKSPACE_2nd) --saveFitResult --saveNLL --robustFit on -n 2ndSimulFit || the_exit "failed to run combine @ data sideband"
+	cd $(oDIR) && source ./scan.numC.fitval.sh && \
+		 combine -M MultiDimFit $(_TMP_HIGGSCOMBINETEST_2nd) --robustFit 1 --algo grid --points 1000 --setParameterRanges numC=$${numC_rangeL},$${numC_rangeR} -P numC -n _scan_numC && \
+		 ../plot1DScan.py --POI numC higgsCombine_scan_numC.MultiDimFit.mH120.root -o scan.numC2nd
+	cd $(oDIR) && source ./scan.numB.fitval.sh && \
+		 combine -M MultiDimFit $(_TMP_HIGGSCOMBINETEST_2nd) --robustFit 1 --algo grid --points 1000 --setParameterRanges numB=$${numB_rangeL},$${numB_rangeR} -P numB -n _scan_numB && \
+		 ../plot1DScan.py --POI numB higgsCombine_scan_numB.MultiDimFit.mH120.root -o scan.numB2nd
+	cd $(oDIR) && source ./$(OUT_FITINFO_BASHVAR) && \
+		 combine -M MultiDimFit $(_TMP_HIGGSCOMBINETEST_2nd) --robustFit 1 --algo grid --points 1000 --setParameterRanges numL=$${numL_rangeL},$${numL_rangeR} -P numL -n _scan_numL && \
+		 ../plot1DScan.py --POI numL higgsCombine_scan_numL.MultiDimFit.mH120.root -o scan.numL2nd
+check9_checktruth: ## check truth value
+	$(call check_dir_existed,$(oDIR))
+	cd $(oDIR) && python3 ../_compare_truth_and_fit_value.py $(iYAMLcvsb) scan.numL2nd.yaml scan.numC2nd.yaml scan.numB2nd.yaml # The result for iYAMLbtag / iYAMLcvsb / iYAMLcvsl are the same
 	cd $(oDIR) && DrawRatioPlotablesWithCMSFormat.py ../input.check.psuedofit_truth.yaml
 
 
@@ -155,13 +189,28 @@ test: $(oDIR)
 
 all: \
 	step10_prepare_histograms \
-	check1_makehisto_content \
 	step2_text2workspace \
 	step3_combine \
 	step4_postfit \
 	check4_postfit \
-	check5_checktruth
+	step5_profiledLL \
+	step6_combinetwice \
+	check9_checktruth
 
+_runagain_: step6_combinetwice check9_checktruth
+
+runagain:  ## run combine twice again, please modify content of scan.numB.yaml and scan.numC.yaml [targetDIR=myprocess/binning_0_0_210_230/]
+	$(call check_defined,targetDIR)
+	oDIR=`basename $(targetDIR)`; \
+		 /bin/rm -rf $$oDIR; cp -r $(targetDIR)  $$oDIR; \
+		 make -f $(self) _runagain_ oDIR=$$oDIR iYAMLcvsb=source.btag_psuedofit_cvsb.yaml 2>&1 > log_$$oDIR  ; \
+		 grep valid_lo log_$$oDIR; mv log_$$oDIR $$oDIR/
+
+	#oDIR=`basename $(targetDIR)`; /bin/rm -rf $(targetDIR); mv  $$oDIR $(targetDIR)
+
+put_runagain_res: # put rerun results to output folder [sourceDIR=hiii/]
+	$(call check_defined,sourceDIR)
+	for a in binned*; do /bin/rm -rf $(sourceDIR)/$$a ; mv $$a $(sourceDIR)/; done
 
 
 IN_ARGS = [opts]
